/**
 * Canonical Composio Google Drive tools — curated from
 * https://docs.composio.dev/toolkits/googledrive
 *
 * Focused on Marqq use cases:
 * - store generated assets
 * - export reports
 * - share files with links
 */

export const GOOGLEDRIVE_TOOL_SLUGS = [
  // Discover / inspect
  "GOOGLEDRIVE_FIND_FILE",
  "GOOGLEDRIVE_FIND_FOLDER",
  "GOOGLEDRIVE_LIST_CHILDREN_V2",
  "GOOGLEDRIVE_GET_FILE_METADATA",
  "GOOGLEDRIVE_GET_ABOUT",
  "GOOGLEDRIVE_LIST_SHARED_DRIVES",
  "GOOGLEDRIVE_GET_DRIVE",

  // Create / upload / organize
  "GOOGLEDRIVE_CREATE_FOLDER",
  "GOOGLEDRIVE_CREATE_FILE",
  "GOOGLEDRIVE_CREATE_FILE_FROM_TEXT",
  "GOOGLEDRIVE_UPLOAD_FILE",
  "GOOGLEDRIVE_UPLOAD_FROM_URL",
  "GOOGLEDRIVE_RESUMABLE_UPLOAD",
  "GOOGLEDRIVE_MOVE_FILE",
  "GOOGLEDRIVE_COPY_FILE_ADVANCED",
  "GOOGLEDRIVE_CREATE_SHORTCUT_TO_FILE",

  // Read / export / update
  "GOOGLEDRIVE_DOWNLOAD_FILE",
  "GOOGLEDRIVE_DOWNLOAD_FILE_OPERATION",
  "GOOGLEDRIVE_EXPORT_GOOGLE_WORKSPACE_FILE",
  "GOOGLEDRIVE_EDIT_FILE",
  "GOOGLEDRIVE_UPDATE_FILE_METADATA_PATCH",

  // Sharing / permissions
  "GOOGLEDRIVE_CREATE_PERMISSION",
  "GOOGLEDRIVE_UPDATE_PERMISSION",
  "GOOGLEDRIVE_LIST_PERMISSIONS",
  "GOOGLEDRIVE_GET_PERMISSION_ID_FOR_EMAIL",

  // Lifecycle
  "GOOGLEDRIVE_TRASH_FILE",
  "GOOGLEDRIVE_UNTRASH_FILE",
  "GOOGLEDRIVE_DELETE_FILE",
];

/** Tools most relevant to saving generated files and reports */
export const GOOGLEDRIVE_STORAGE_TOOLS = [
  "GOOGLEDRIVE_FIND_FOLDER",
  "GOOGLEDRIVE_CREATE_FOLDER",
  "GOOGLEDRIVE_CREATE_FILE_FROM_TEXT",
  "GOOGLEDRIVE_CREATE_FILE",
  "GOOGLEDRIVE_UPLOAD_FILE",
  "GOOGLEDRIVE_UPLOAD_FROM_URL",
  "GOOGLEDRIVE_RESUMABLE_UPLOAD",
  "GOOGLEDRIVE_MOVE_FILE",
];

/** Tools most relevant to sharing files with links / access */
export const GOOGLEDRIVE_SHARING_TOOLS = [
  "GOOGLEDRIVE_GET_FILE_METADATA",
  "GOOGLEDRIVE_CREATE_PERMISSION",
  "GOOGLEDRIVE_UPDATE_PERMISSION",
  "GOOGLEDRIVE_LIST_PERMISSIONS",
  "GOOGLEDRIVE_GET_PERMISSION_ID_FOR_EMAIL",
];
