/**
 * Canonical Composio Google Sheets tools — curated for Marqq
 * (CRM / voice outcomes export, create+append, upsert).
 */

export const GOOGLESHEETS_TOOL_SLUGS = [
  // Discover / read
  'GOOGLESHEETS_SEARCH_SPREADSHEETS',
  'GOOGLESHEETS_GET_SPREADSHEET_INFO',
  'GOOGLESHEETS_GET_SHEET_NAMES',
  'GOOGLESHEETS_VALUES_GET',
  'GOOGLESHEETS_BATCH_GET',
  'GOOGLESHEETS_LIST_TABLES',
  'GOOGLESHEETS_GET_TABLE_SCHEMA',
  'GOOGLESHEETS_QUERY_TABLE',
  'GOOGLESHEETS_LOOKUP_SPREADSHEET_ROW',
  'GOOGLESHEETS_EXECUTE_SQL',

  // Create / write
  'GOOGLESHEETS_CREATE_GOOGLE_SHEET1',
  'GOOGLESHEETS_ADD_SHEET',
  'GOOGLESHEETS_SHEET_FROM_JSON',
  'GOOGLESHEETS_CREATE_SPREADSHEET_ROW',
  'GOOGLESHEETS_CREATE_SPREADSHEET_COLUMN',
  'GOOGLESHEETS_SPREADSHEETS_VALUES_APPEND',
  'GOOGLESHEETS_VALUES_UPDATE',
  'GOOGLESHEETS_UPDATE_VALUES_BATCH',
  'GOOGLESHEETS_UPSERT_ROWS',

  // Light ops
  'GOOGLESHEETS_CLEAR_VALUES',
  'GOOGLESHEETS_FIND_REPLACE',
  'GOOGLESHEETS_SORT_RANGE',
  'GOOGLESHEETS_SET_BASIC_FILTER',
]

/** Tools used by Push to Sheet go-live */
export const GOOGLESHEETS_PUSH_TOOLS = [
  'GOOGLESHEETS_SEARCH_SPREADSHEETS',
  'GOOGLESHEETS_GET_SPREADSHEET_INFO',
  'GOOGLESHEETS_GET_SHEET_NAMES',
  'GOOGLESHEETS_CREATE_GOOGLE_SHEET1',
  'GOOGLESHEETS_SHEET_FROM_JSON',
  'GOOGLESHEETS_ADD_SHEET',
  'GOOGLESHEETS_SPREADSHEETS_VALUES_APPEND',
  'GOOGLESHEETS_UPSERT_ROWS',
  'GOOGLESHEETS_VALUES_GET',
]
