/**
 * Canonical Composio Klaviyo toolkit — curated for Marqq
 * (newsletter go-live, profiles/lists, templates, flows, reporting).
 * Do not invent slugs; keep in sync with Composio Klaviyo catalog.
 */

/**
 * Agent / go-live allowlist.
 * Excludes catalog/ecommerce, coupons, push tokens, and bulk catalog job sprawl.
 */
export const KLAVIYO_TOOL_SLUGS = [
  // ── Campaign / newsletter go-live ─────────────────────────────────────────
  'KLAVIYO_CREATE_CAMPAIGN',
  'KLAVIYO_CREATE_CAMPAIGN_CLONE',
  'KLAVIYO_CREATE_CAMPAIGN_SEND_JOB',
  'KLAVIYO_CANCEL_CAMPAIGN_SEND',
  'KLAVIYO_CREATE_CAMPAIGN_RECIPIENT_ESTIMATION_JOB',
  'KLAVIYO_ASSIGN_CAMPAIGN_MESSAGE_TEMPLATE',
  'KLAVIYO_UPDATE_CAMPAIGN',
  'KLAVIYO_UPDATE_CAMPAIGN_MESSAGE',
  'KLAVIYO_GET_CAMPAIGN',
  'KLAVIYO_GET_CAMPAIGNS',
  'KLAVIYO_GET_CAMPAIGN_CAMPAIGN_MESSAGES',
  'KLAVIYO_GET_CAMPAIGN_MESSAGE',
  'KLAVIYO_GET_CAMPAIGN_MESSAGE_TEMPLATE',
  'KLAVIYO_GET_CAMPAIGN_RECIPIENT_ESTIMATION',
  'KLAVIYO_GET_CAMPAIGN_RECIPIENT_ESTIMATION_JOB',
  'KLAVIYO_GET_CAMPAIGN_SEND_JOB',
  'KLAVIYO_GET_CAMPAIGN_TAGS',
  'KLAVIYO_DELETE_CAMPAIGN',
  'KLAVIYO_QUERY_CAMPAIGN_VALUES',

  // ── Templates ─────────────────────────────────────────────────────────────
  'KLAVIYO_CREATE_TEMPLATE',
  'KLAVIYO_CREATE_TEMPLATE_CLONE',
  'KLAVIYO_CREATE_TEMPLATE_RENDER',
  'KLAVIYO_GET_TEMPLATE',
  'KLAVIYO_GET_TEMPLATES',
  'KLAVIYO_UPDATE_TEMPLATE',
  'KLAVIYO_DELETE_TEMPLATE',

  // ── Lists / segments / profiles / subscribe ───────────────────────────────
  'KLAVIYO_GET_LISTS',
  'KLAVIYO_GET_LIST',
  'KLAVIYO_CREATE_LIST',
  'KLAVIYO_UPDATE_LIST',
  'KLAVIYO_GET_LIST_PROFILES',
  'KLAVIYO_ADD_PROFILE_TO_LIST',
  'KLAVIYO_REMOVE_PROFILE_FROM_LIST',
  'KLAVIYO_GET_SEGMENTS',
  'KLAVIYO_GET_SEGMENT',
  'KLAVIYO_CREATE_SEGMENT',
  'KLAVIYO_UPDATE_SEGMENT',
  'KLAVIYO_GET_SEGMENT_PROFILES',
  'KLAVIYO_CREATE_PROFILE',
  'KLAVIYO_CREATE_OR_UPDATE_PROFILE',
  'KLAVIYO_CREATE_OR_UPDATE_CLIENT_PROFILE',
  'KLAVIYO_UPDATE_PROFILE',
  'KLAVIYO_GET_PROFILE',
  'KLAVIYO_GET_PROFILES',
  'KLAVIYO_GET_PROFILE_LISTS',
  'KLAVIYO_GET_PROFILE_SEGMENTS',
  'KLAVIYO_MERGE_PROFILES',
  'KLAVIYO_SUBSCRIBE_PROFILES',
  'KLAVIYO_CREATE_CLIENT_SUBSCRIPTION',
  'KLAVIYO_UNSUBSCRIBE_PROFILES',
  'KLAVIYO_UNSUBSCRIBE_PROFILES_BULK',
  'KLAVIYO_SUPPRESS_PROFILES',
  'KLAVIYO_UNSUPPRESS_PROFILES',
  'KLAVIYO_UNSUPPRESS_PROFILES_BULK',
  'KLAVIYO_SPAWN_BULK_PROFILE_IMPORT_JOB',
  'KLAVIYO_GET_BULK_PROFILE_IMPORT_JOB',
  'KLAVIYO_GET_BULK_PROFILE_IMPORT_JOBS',
  'KLAVIYO_GET_BULK_PROFILE_IMPORT_JOB_ERRORS',
  'KLAVIYO_GET_BULK_PROFILE_IMPORT_JOB_PROFILES',
  'KLAVIYO_GET_BULK_PROFILE_IMPORT_JOB_LISTS',

  // ── Tags (campaign / list org) ────────────────────────────────────────────
  'KLAVIYO_CREATE_TAG',
  'KLAVIYO_CREATE_TAG_GROUP',
  'KLAVIYO_CREATE_TAG_RELATIONSHIPS',
  'KLAVIYO_GET_TAGS',
  'KLAVIYO_GET_TAG',
  'KLAVIYO_GET_TAG_GROUPS',
  'KLAVIYO_UPDATE_TAG',
  'KLAVIYO_UPDATE_TAG_GROUP',

  // ── Flows (email sequences) ───────────────────────────────────────────────
  'KLAVIYO_GET_FLOWS',
  'KLAVIYO_GET_FLOW',
  'KLAVIYO_GET_FLOW_FLOW_ACTIONS',
  'KLAVIYO_GET_FLOW_ACTION',
  'KLAVIYO_GET_FLOW_ACTION_MESSAGES',
  'KLAVIYO_GET_FLOW_MESSAGE',
  'KLAVIYO_GET_FLOW_MESSAGE_TEMPLATE',
  'KLAVIYO_UPDATE_FLOW_STATUS',
  'KLAVIYO_QUERY_FLOW_SERIES',
  'KLAVIYO_QUERY_FLOW_VALUES',

  // ── Events / metrics (engagement + attribution) ───────────────────────────
  'KLAVIYO_CREATE_EVENT',
  'KLAVIYO_BULK_CREATE_EVENTS',
  'KLAVIYO_CREATE_CLIENT_EVENT2',
  'KLAVIYO_BULK_CREATE_CLIENT_EVENTS',
  'KLAVIYO_GET_EVENTS',
  'KLAVIYO_GET_EVENT',
  'KLAVIYO_GET_EVENT_PROFILE',
  'KLAVIYO_GET_EVENT_METRIC',
  'KLAVIYO_GET_METRICS',
  'KLAVIYO_GET_METRIC',
  'KLAVIYO_QUERY_METRIC_AGGREGATES',

  // ── Forms (lead capture ↔ landing) ────────────────────────────────────────
  'KLAVIYO_GET_FORMS',
  'KLAVIYO_GET_FORM',
  'KLAVIYO_GET_FORM_VERSION',
  'KLAVIYO_GET_VERSIONS_FOR_FORM',

  // ── Images (campaign assets) ──────────────────────────────────────────────
  'KLAVIYO_GET_IMAGES',
  'KLAVIYO_GET_IMAGE',
  'KLAVIYO_UPLOAD_IMAGE_FROM_FILE',
  'KLAVIYO_UPLOAD_IMAGE_FROM_URL',
  'KLAVIYO_UPDATE_IMAGE',

  // ── Webhooks ──────────────────────────────────────────────────────────────
  'KLAVIYO_CREATE_WEBHOOK',
  'KLAVIYO_GET_WEBHOOKS',
  'KLAVIYO_GET_WEBHOOK',
  'KLAVIYO_GET_WEBHOOK_TOPICS',
  'KLAVIYO_GET_WEBHOOK_TOPIC',
  'KLAVIYO_UPDATE_WEBHOOK',
  'KLAVIYO_DELETE_WEBHOOK',

  // ── Account health ────────────────────────────────────────────────────────
  'KLAVIYO_GET_ACCOUNT',
  'KLAVIYO_GET_ACCOUNTS',
]

/** Core tools used by newsletter go-live path */
export const KLAVIYO_NEWSLETTER_TOOLS = [
  'KLAVIYO_CREATE_TEMPLATE',
  'KLAVIYO_CREATE_CAMPAIGN',
  'KLAVIYO_ASSIGN_CAMPAIGN_MESSAGE_TEMPLATE',
  'KLAVIYO_CREATE_CAMPAIGN_SEND_JOB',
  'KLAVIYO_GET_LISTS',
  'KLAVIYO_CANCEL_CAMPAIGN_SEND',
]
