/**
 * Canonical Composio Mailchimp toolkit — curated for Marqq
 * (newsletter go-live, audiences, landing pages, automations, reporting).
 * Do not invent slugs; keep in sync with Composio Mailchimp catalog.
 */

/** Webhook triggers — each requires trigger_config.list_id */
export const MAILCHIMP_TRIGGER_SLUGS = [
  'MAILCHIMP_CAMPAIGN_TRIGGER',
  'MAILCHIMP_PROFILE_UPDATE_TRIGGER',
  'MAILCHIMP_SUBSCRIBE_TRIGGER',
  'MAILCHIMP_UNSUBSCRIBE_TRIGGER',
]

export const MAILCHIMP_TRIGGER_META = {
  MAILCHIMP_CAMPAIGN_TRIGGER: {
    name: 'Campaign Trigger',
    type: 'webhook',
    description: 'Fired when a campaign is sent or experiences an event',
  },
  MAILCHIMP_PROFILE_UPDATE_TRIGGER: {
    name: 'Profile Update Trigger',
    type: 'webhook',
    description: "Fired when a subscriber's profile is updated",
  },
  MAILCHIMP_SUBSCRIBE_TRIGGER: {
    name: 'Subscribe Trigger',
    type: 'webhook',
    description: 'Fired when someone subscribes to an audience',
  },
  MAILCHIMP_UNSUBSCRIBE_TRIGGER: {
    name: 'Unsubscribe Trigger',
    type: 'webhook',
    description: 'Fired when someone unsubscribes from an audience',
  },
}

/** Audience listing for Settings picker + trigger registration */
export const MAILCHIMP_AUDIENCE_TOOLS = [
  'MAILCHIMP_GET_LISTS_INFO',
  'MAILCHIMP_GET_LIST_INFO',
]

/**
 * Agent / go-live allowlist — newsletter + LP + audience ops only.
 * Excludes ecommerce (cart/store/product/order), FB ads-in-MC, folders, domains.
 */
export const MAILCHIMP_TOOL_SLUGS = [
  // ── Campaign create / send (newsletter go-live) ───────────────────────────
  'MAILCHIMP_ADD_CAMPAIGN',
  'MAILCHIMP_CREATE_CAMPAIGN', // legacy alias if present in account toolkit
  'MAILCHIMP_CREATE_A_SURVEY_CAMPAIGN',
  'MAILCHIMP_SET_CAMPAIGN_CONTENT',
  'MAILCHIMP_SEND_CAMPAIGN',
  'MAILCHIMP_SEND_TEST_EMAIL',
  'MAILCHIMP_SCHEDULE_CAMPAIGN',
  'MAILCHIMP_UNSCHEDULE_CAMPAIGN',
  'MAILCHIMP_CANCEL_CAMPAIGN',
  'MAILCHIMP_UPDATE_CAMPAIGN_SETTINGS',
  'MAILCHIMP_REPLICATE_CAMPAIGN',
  'MAILCHIMP_RESEND_CAMPAIGN',
  'MAILCHIMP_GET_CAMPAIGN_CONTENT',
  'MAILCHIMP_GET_CAMPAIGN_INFO',
  'MAILCHIMP_GET_CAMPAIGN_SEND_CHECKLIST',
  'MAILCHIMP_LIST_CAMPAIGNS',
  'MAILCHIMP_SEARCH_CAMPAIGNS',
  'MAILCHIMP_VIEW_DEFAULT_CONTENT',

  // ── Audiences / members / tags / segments ─────────────────────────────────
  'MAILCHIMP_GET_LISTS_INFO',
  'MAILCHIMP_GET_LIST_INFO',
  'MAILCHIMP_ADD_CONTACT_TO_AUDIENCE',
  'MAILCHIMP_ADD_OR_UPDATE_LIST_MEMBER',
  'MAILCHIMP_BATCH_SUBSCRIBE_OR_UNSUBSCRIBE',
  'MAILCHIMP_BATCH_ADD_OR_REMOVE_MEMBERS',
  'MAILCHIMP_UPDATE_LIST_MEMBER',
  'MAILCHIMP_UPDATE_AUDIENCES_CONTACTS',
  'MAILCHIMP_LIST_MEMBERS_INFO',
  'MAILCHIMP_GET_MEMBER_INFO',
  'MAILCHIMP_GET_AUDIENCES_CONTACTS',
  'MAILCHIMP_GET_AUDIENCES_CONTACTS_DETAIL',
  'MAILCHIMP_SEARCH_MEMBERS',
  'MAILCHIMP_LIST_UNSUBSCRIBED_MEMBERS',
  'MAILCHIMP_GET_UNSUBSCRIBED_MEMBER',
  'MAILCHIMP_ADD_OR_REMOVE_MEMBER_TAGS',
  'MAILCHIMP_LIST_MEMBER_TAGS',
  'MAILCHIMP_SEARCH_FOR_TAGS_ON_A_LIST_BY_NAME',
  'MAILCHIMP_ADD_SEGMENT',
  'MAILCHIMP_LIST_SEGMENTS',
  'MAILCHIMP_GET_SEGMENT_INFO',
  'MAILCHIMP_UPDATE_LISTS_SEGMENTS',
  'MAILCHIMP_LIST_MEMBERS_IN_SEGMENT',
  'MAILCHIMP_ADD_MEMBER_TO_SEGMENT',
  'MAILCHIMP_REMOVE_LIST_MEMBER_FROM_SEGMENT',
  'MAILCHIMP_LIST_GROWTH_HISTORY_DATA',
  'MAILCHIMP_GET_GROWTH_HISTORY_BY_MONTH',
  'MAILCHIMP_LIST_MERGE_FIELDS',
  'MAILCHIMP_ADD_MERGE_FIELD',

  // ── Templates ─────────────────────────────────────────────────────────────
  'MAILCHIMP_ADD_TEMPLATE',
  'MAILCHIMP_LIST_TEMPLATES',
  'MAILCHIMP_GET_TEMPLATE_INFO',
  'MAILCHIMP_UPDATE_TEMPLATE',

  // ── Landing pages (alt CMS publish path) ──────────────────────────────────
  'MAILCHIMP_ADD_LANDING_PAGE',
  'MAILCHIMP_LIST_LANDING_PAGES',
  'MAILCHIMP_GET_LANDING_PAGE_INFO',
  'MAILCHIMP_GET_LANDING_PAGE_CONTENT',
  'MAILCHIMP_UPDATE_LANDING_PAGE',
  'MAILCHIMP_PUBLISH_LANDING_PAGE',
  'MAILCHIMP_UNPUBLISH_LANDING_PAGE',
  'MAILCHIMP_GET_LANDING_PAGE_REPORT',
  'MAILCHIMP_LIST_LANDING_PAGES_REPORTS',

  // ── Automations / journeys ────────────────────────────────────────────────
  'MAILCHIMP_ADD_AUTOMATION',
  'MAILCHIMP_LIST_AUTOMATIONS',
  'MAILCHIMP_GET_AUTOMATION_INFO',
  'MAILCHIMP_LIST_AUTOMATED_EMAILS',
  'MAILCHIMP_GET_WORKFLOW_EMAIL_INFO',
  'MAILCHIMP_UPDATE_WORKFLOW_EMAIL',
  'MAILCHIMP_START_AUTOMATED_EMAIL',
  'MAILCHIMP_START_AUTOMATION_EMAILS',
  'MAILCHIMP_PAUSE_AUTOMATED_EMAIL',
  'MAILCHIMP_PAUSE_AUTOMATION_EMAILS',
  'MAILCHIMP_ADD_SUBSCRIBER_TO_WORKFLOW_EMAIL',
  'MAILCHIMP_REMOVE_SUBSCRIBER_FROM_WORKFLOW',
  'MAILCHIMP_LIST_AUTOMATED_EMAIL_SUBSCRIBERS',
  'MAILCHIMP_LIST_SUBSCRIBERS_REMOVED_FROM_WORKFLOW',
  'MAILCHIMP_GET_SUBSCRIBER_REMOVED_FROM_WORKFLOW',
  'MAILCHIMP_CUSTOMER_JOURNEYS_API_TRIGGER_FOR_A_CONTACT',

  // ── Reporting / engagement ────────────────────────────────────────────────
  'MAILCHIMP_LIST_CAMPAIGN_REPORTS',
  'MAILCHIMP_GET_CAMPAIGN_REPORT',
  'MAILCHIMP_LIST_EMAIL_ACTIVITY',
  'MAILCHIMP_GET_SUBSCRIBER_EMAIL_ACTIVITY',
  'MAILCHIMP_LIST_CAMPAIGN_OPEN_DETAILS',
  'MAILCHIMP_GET_OPENED_CAMPAIGN_SUBSCRIBER',
  'MAILCHIMP_LIST_CLICKED_LINK_SUBSCRIBERS',
  'MAILCHIMP_GET_CLICKED_LINK_SUBSCRIBER',
  'MAILCHIMP_GET_CAMPAIGN_LINK_DETAILS',
  'MAILCHIMP_LIST_CAMPAIGN_RECIPIENTS',
  'MAILCHIMP_GET_CAMPAIGN_RECIPIENT_INFO',
  'MAILCHIMP_LIST_TOP_OPEN_ACTIVITIES',
  'MAILCHIMP_LIST_DOMAIN_PERFORMANCE_STATS',
  'MAILCHIMP_LIST_MEMBER_EVENTS',
  'MAILCHIMP_LIST_MEMBER_GOAL_EVENTS',
  'MAILCHIMP_LIST_RECENT_ACTIVITY',
  'MAILCHIMP_VIEW_RECENT_ACTIVITY',
  'MAILCHIMP_LIST_TOP_EMAIL_CLIENTS',

  // ── Webhooks (native MC; Composio triggers preferred for Marqq) ────────────
  'MAILCHIMP_ADD_WEBHOOK',
  'MAILCHIMP_LIST_WEBHOOKS',
  'MAILCHIMP_GET_WEBHOOK_INFO',
  'MAILCHIMP_UPDATE_WEBHOOK',
  'MAILCHIMP_DELETE_WEBHOOK',
  'MAILCHIMP_ADD_BATCH_WEBHOOK',
  'MAILCHIMP_LIST_BATCH_WEBHOOKS',
  'MAILCHIMP_GET_BATCH_WEBHOOK_INFO',
  'MAILCHIMP_UPDATE_BATCH_WEBHOOK',
  'MAILCHIMP_DELETE_BATCH_WEBHOOK',

  // ── Assets / signup / health ──────────────────────────────────────────────
  'MAILCHIMP_ADD_FILE',
  'MAILCHIMP_LIST_STORED_FILES',
  'MAILCHIMP_GET_FILE',
  'MAILCHIMP_LIST_SIGNUP_FORMS',
  'MAILCHIMP_CUSTOMIZE_SIGNUP_FORM',
  'MAILCHIMP_PING',
  'MAILCHIMP_LIST_API_ROOT_RESOURCES',
]

/** Core tools used by newsletter go-live path */
export const MAILCHIMP_NEWSLETTER_TOOLS = [
  'MAILCHIMP_ADD_CAMPAIGN',
  'MAILCHIMP_CREATE_CAMPAIGN',
  'MAILCHIMP_CREATE_A_SURVEY_CAMPAIGN',
  'MAILCHIMP_SET_CAMPAIGN_CONTENT',
  'MAILCHIMP_SEND_CAMPAIGN',
  'MAILCHIMP_SEND_TEST_EMAIL',
  'MAILCHIMP_GET_LISTS_INFO',
  'MAILCHIMP_SCHEDULE_CAMPAIGN',
]

export function isMailchimpTriggerSlug(slug = '') {
  const s = String(slug || '').toUpperCase()
  return (
    MAILCHIMP_TRIGGER_SLUGS.includes(s) ||
    (s.startsWith('MAILCHIMP_') && s.endsWith('_TRIGGER'))
  )
}
