/**
 * Canonical Composio Webflow tools — curated from the live toolkit
 * for Marqq CMS publish (blog / landing), not ecommerce.
 */

/** Full CMS + publish surface (agent allowlist). No order/inventory tools. */
export const WEBFLOW_TOOL_SLUGS = [
  // Sites / collections / pages — discover
  'WEBFLOW_LIST_WEBFLOW_SITES',
  'WEBFLOW_GET_SITE_INFO',
  'WEBFLOW_LIST_COLLECTIONS',
  'WEBFLOW_GET_COLLECTION',
  'WEBFLOW_LIST_COLLECTION_ITEMS',
  'WEBFLOW_LIST_LIVE_COLLECTION_ITEMS',
  'WEBFLOW_GET_COLLECTION_ITEM',
  'WEBFLOW_GET_LIVE_COLLECTION_ITEM',
  'WEBFLOW_LIST_PAGES',
  'WEBFLOW_GET_PAGE',
  'WEBFLOW_GET_PAGE_DOM',
  'WEBFLOW_LIST_CUSTOM_DOMAINS',
  'WEBFLOW_GET_CUSTOM_DOMAINS',
  'WEBFLOW_GET_TOKEN_AUTHORIZED_BY',
  'WEBFLOW_LIST_FORMS',
  'WEBFLOW_LIST_FORM_SUBMISSIONS',

  // Assets
  'WEBFLOW_LIST_ASSETS',
  'WEBFLOW_LIST_ASSET_FOLDERS',
  'WEBFLOW_GET_ASSET',
  'WEBFLOW_GET_ASSET_FOLDER',
  'WEBFLOW_CREATE_ASSET',
  'WEBFLOW_CREATE_ASSET_FOLDER',
  'WEBFLOW_UPLOAD_ASSET',
  'WEBFLOW_DELETE_ASSET',

  // Collection schema (setup)
  'WEBFLOW_CREATE_COLLECTION',
  'WEBFLOW_CREATE_COLLECTION_FIELD',
  'WEBFLOW_UPDATE_COLLECTION_FIELD',

  // Create / update / publish items
  'WEBFLOW_CREATE_COLLECTION_ITEM',
  'WEBFLOW_CREATE_LIVE_COLLECTION_ITEM',
  'WEBFLOW_CREATE_BULK_COLLECTION_ITEMS',
  'WEBFLOW_UPDATE_COLLECTION_ITEM_V2',
  'WEBFLOW_UPDATE_COLLECTION_ITEMS_BULK',
  'WEBFLOW_UPDATE_LIVE_COLLECTION_ITEM',
  'WEBFLOW_UPDATE_LIVE_COLLECTION_ITEMS',
  'WEBFLOW_PUBLISH_COLLECTION_ITEMS',
  'WEBFLOW_PUBLISH_SITE',
  'WEBFLOW_UNPUBLISH_LIVE_COLLECTION_ITEM',
  'WEBFLOW_UNPUBLISH_LIVE_COLLECTION_ITEMS',
  'WEBFLOW_DELETE_COLLECTION_ITEM',
  'WEBFLOW_DELETE_COLLECTION_ITEMS',

  // Page / site metadata
  'WEBFLOW_UPDATE_PAGE',
  'WEBFLOW_UPDATE_PAGE_METADATA',
  'WEBFLOW_UPDATE_SITE',

  // Deprecated alias still seen in older flows
  'WEBFLOW_UPDATE_COLLECTION_ITEM',
]

/**
 * Tools used by blog / landing-page go-live publish path.
 * Prefer live create → publish items → publish site.
 */
export const WEBFLOW_PUBLISH_TOOLS = [
  'WEBFLOW_LIST_WEBFLOW_SITES',
  'WEBFLOW_GET_SITE_INFO',
  'WEBFLOW_LIST_CUSTOM_DOMAINS',
  'WEBFLOW_GET_CUSTOM_DOMAINS',
  'WEBFLOW_LIST_COLLECTIONS',
  'WEBFLOW_GET_COLLECTION',
  'WEBFLOW_LIST_COLLECTION_ITEMS',
  'WEBFLOW_GET_COLLECTION_ITEM',
  'WEBFLOW_GET_LIVE_COLLECTION_ITEM',
  'WEBFLOW_CREATE_COLLECTION_ITEM',
  'WEBFLOW_CREATE_LIVE_COLLECTION_ITEM',
  'WEBFLOW_UPDATE_COLLECTION_ITEM_V2',
  'WEBFLOW_UPDATE_LIVE_COLLECTION_ITEM',
  'WEBFLOW_PUBLISH_COLLECTION_ITEMS',
  'WEBFLOW_PUBLISH_SITE',
  'WEBFLOW_UPLOAD_ASSET',
  'WEBFLOW_CREATE_ASSET',
  'WEBFLOW_LIST_PAGES',
  'WEBFLOW_UPDATE_PAGE_METADATA',
]
